Its that time again!
JulianusIV/LathBot pull request #57
Opened 2024-09-04 02:45 UTC by Ryguy6001

I added some more stuff to the pat, and slap commands, some from tophat, also me. btw tophat needs help fixing his F2A for lathbot.

2024-09-04 02:51 UTC, Ryguy6001 commented
Don't pull this! I need to add something in the morning for me.

2024-09-04 16:25 UTC, JulianusIV requested changes
Please update the source branch, not all commits from the target branch are included yet!

2024-09-04 16:25 UTC, JulianusIV commented on LathBotFront/Commands/ReactionCommands.cs
> +using System.Runtime;
why?

2024-09-04 16:25 UTC, JulianusIV commented on LathBotFront/Commands/ReactionCommands.cs
> +            await ctx.Channel.SendMessageAsync("Boss man! (even tho the whole senate technically are all equal but i am keeping this for the laughs, also he is the actual owner)");
no need to state this really
```suggestion
            await ctx.Channel.SendMessageAsync("Boss man! (even tho the whole senate technically are all equal but i am keeping this for the laughs)");
```

2024-09-04 16:25 UTC, JulianusIV commented on LathBotFront/Commands/ReactionCommands.cs
> +                await ctx.RespondAsync($"Tophat does not enjoy this, please stop.");//Tophat also requested this for himself.
too bad, everyone can be pat, please remove
he can yell at people who try individually

2024-09-04 16:26 UTC, JulianusIV commented
also in the future, if you want to publish a pr that is still being worked on you can also use drafts: 
- https://github.blog/news-insights/product-news/introducing-draft-pull-requests/
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

2024-09-04 17:50 UTC, JulianusIV commented on LathBotFront/Commands/ReactionCommands.cs
> +                await ctx.RespondAsync($"Ryguy doesn't like getting patted.");
Overlooked that earlier sorry, but same for you as with tophat, noone gets to not get pat, just go yelling at people that try to do so

2024-09-04 20:15 UTC, Ryguy6001 commented
> Please update the source branch, not all commits from the target branch are included yet!

Darn it

2024-09-05 15:45 UTC, JulianusIV approved these changes

2024-09-05 15:45 UTC, merged